### ISSUE TITLE
'An unknown error occurred' on block import in Craft 3.1.x

### ISSUE THREAD

**Issue by stevehurst** [charliedevelopment/craft3-blockonomicon#6]
I'm not able to import an exported block using Blockonomicon in Craft 3.1.x. I get an 'An unknown error occurred' popup.

I'm on Blockonomicon 1.1.4 and Craft 3.1.12

**Comment by sbossarte** [comment]
From some initial investigation it looks like this is related to Craft's new 'project.yaml' system. Will note here once things get resolved or if we can further identify the issue.

**Comment by sbossarte** [comment]
This should hopefully be fixed with b9c0976b91febb5cf96f9aed6628228275490cff .

Craft's new system added a few properties that needed to be set on fields before saving, which wasn't already being handled by Blockonomicon, because it was operating under the assumption that Craft would call anything necessary beforehand. Now it calls the beforeSave function when importing blocks, which should work better with the new systems in place in Craft 3.1.
